apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
    - port: 80
      targetPort: 80
  labels:
    app: hello
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-kenzan:$BUILD_TAG
        name: hello
        ports:
        - containerPort: 80
          name: hello
