apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app.kubernetes.io/name: hello
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: hello
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app.kubernetes.io/name: hello
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-kenzan:latest
        name: hello
        ports:
        - containerPort: 80
          name: hello
